// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpspjbapdhufjhxvbbov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwc3BqYmFwZGh1ZmpoeHZiYm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjY0MTcsImV4cCI6MjA2NzY0MjQxN30.eFHAnJRxF1yv64jzsr1V1JXE_5Ozth8W3Drnf01zaqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});